from datetime import datetime, timezone
from threading import Lock
from uuid import uuid4

from app.schemas.inference import (
    AnalysisResult,
    CreateJobRequest,
    CreateJobResponse,
    JobStatusResponse,
)


class InferenceService:
    def __init__(self) -> None:
        self._jobs: dict[str, JobStatusResponse] = {}
        self._lock = Lock()

    def create_job(self, request: CreateJobRequest) -> CreateJobResponse:
        job_id = f"job-{request.report_id}-{uuid4().hex[:8]}"
        now = datetime.now(timezone.utc)

        result = AnalysisResult(
            status="Normal",
            confidence=93,
            findings=[
                "No focal air-space opacity identified.",
                "Cardiomediastinal silhouette remains within expected size limits.",
                "Pleural spaces appear clear without visible effusion.",
            ],
            recommendations=[
                "Continue routine clinical review.",
                "Escalate for radiologist validation if symptoms persist.",
            ],
            ai_analysis=(
                "This placeholder inference service completed a mock chest X-ray analysis and did not detect acute "
                "cardiopulmonary abnormality."
            ),
            raw={
                "model": "placeholder-cnn",
                "scores": {
                    "normal": 0.93,
                    "abnormal": 0.07,
                },
            },
        )

        job = JobStatusResponse(
            job_id=job_id,
            status="completed",
            created_at=now,
            updated_at=now,
            result=result,
            message="Mock inference result generated by FastAPI scaffold.",
        )

        with self._lock:
            self._jobs[job_id] = job

        return CreateJobResponse(
            job_id=job_id,
            status=job.status,
            result=job.result,
            message=job.message,
        )

    def get_job(self, job_id: str) -> JobStatusResponse | None:
        with self._lock:
            return self._jobs.get(job_id)


inference_service = InferenceService()

