from datetime import datetime, timezone
from threading import Lock
from typing import Any
from uuid import uuid4

from app.core.config import settings
from app.schemas.inference import (
    AnalysisResult,
    CreateJobRequest,
    CreateJobResponse,
    JobStatusResponse,
)
from app.services.model_runtime import LocalModelRuntime


class InferenceService:
    def __init__(self) -> None:
        self._jobs: dict[str, JobStatusResponse] = {}
        self._lock = Lock()
        self._runtime: LocalModelRuntime | None = None
        self._runtime_error: str | None = None
        self._settings = settings

    def create_job(self, request: CreateJobRequest) -> CreateJobResponse:
        job_id = f"job-{request.report_id}-{uuid4().hex[:8]}"
        now = datetime.now(timezone.utc)

        result = AnalysisResult(**self._build_result(request))

        job = JobStatusResponse(
            job_id=job_id,
            status="completed",
            created_at=now,
            updated_at=now,
            result=result,
            message=(
                "Mock inference result generated by FastAPI scaffold."
                if self._settings.use_mock
                else "Local model inference completed successfully."
            ),
        )

        with self._lock:
            self._jobs[job_id] = job

        return CreateJobResponse(
            job_id=job_id,
            status=job.status,
            result=job.result,
            message=job.message,
        )

    def get_job(self, job_id: str) -> JobStatusResponse | None:
        with self._lock:
            return self._jobs.get(job_id)

    def describe(self) -> dict[str, Any]:
        runtime = self._runtime
        if runtime is None and not self._settings.use_mock:
            try:
                runtime = self._get_runtime()
            except Exception:
                runtime = None
        return {
            "mode": "mock" if self._settings.use_mock else "model",
            "model_name": self._settings.model_name,
            "model_loaded": runtime is not None,
            "model_checkpoint_path": (
                str(self._settings.model_checkpoint_path.resolve())
                if self._settings.model_checkpoint_path is not None
                else None
            ),
            "device": runtime.metadata.device if runtime is not None else None,
            "runtime_error": self._runtime_error,
        }

    def _build_result(self, request: CreateJobRequest) -> dict[str, Any]:
        if self._settings.use_mock:
            return {
                "status": "Normal",
                "confidence": 93,
                "findings": [
                    "No focal air-space opacity identified.",
                    "Cardiomediastinal silhouette remains within expected size limits.",
                    "Pleural spaces appear clear without visible effusion.",
                ],
                "recommendations": [
                    "Continue routine clinical review.",
                    "Escalate for radiologist validation if symptoms persist.",
                ],
                "ai_analysis": (
                    "This placeholder inference service completed a mock chest X-ray analysis and did not detect acute "
                    "cardiopulmonary abnormality."
                ),
                "raw": {
                    "model": "placeholder-cnn",
                    "scores": {
                        "normal": 0.93,
                        "abnormal": 0.07,
                    },
                },
            }

        runtime = self._get_runtime()
        return runtime.predict(request.object_key)

    def _get_runtime(self) -> LocalModelRuntime:
        if self._runtime is not None:
            return self._runtime

        with self._lock:
            if self._runtime is not None:
                return self._runtime
            try:
                self._runtime = LocalModelRuntime(self._settings)
                self._runtime_error = None
                return self._runtime
            except Exception as exc:
                self._runtime_error = str(exc)
                raise RuntimeError(f"failed to initialize local model runtime: {exc}") from exc


inference_service = InferenceService()
