from datetime import datetime, timezone
from threading import Lock
from typing import Any
from uuid import uuid4

from app.core.config import settings
from app.schemas.inference import (
    AnalysisResult,
    CreateJobRequest,
    CreateJobResponse,
    JobStatusResponse,
)
from app.services.model_runtime import LocalModelRuntime


class InferenceService:
    def __init__(self) -> None:
        self._jobs: dict[str, JobStatusResponse] = {}
        self._lock = Lock()
        self._runtime: LocalModelRuntime | None = None
        self._runtime_error: str | None = None
        self._settings = settings

    def create_job(self, request: CreateJobRequest) -> CreateJobResponse:
        job_id = f"job-{request.report_id}-{uuid4().hex[:8]}"
        now = datetime.now(timezone.utc)

        result = AnalysisResult(**self._build_result(request))

        job = JobStatusResponse(
            job_id=job_id,
            status="completed",
            created_at=now,
            updated_at=now,
            result=result,
            message=(
                "Mock inference result generated by FastAPI scaffold."
                if self._settings.use_mock
                else "Local model inference completed successfully."
            ),
        )

        with self._lock:
            self._jobs[job_id] = job

        return CreateJobResponse(
            job_id=job_id,
            status=job.status,
            result=job.result,
            message=job.message,
        )

    def get_job(self, job_id: str) -> JobStatusResponse | None:
        with self._lock:
            return self._jobs.get(job_id)

    def describe(self) -> dict[str, Any]:
        runtime = self._runtime
        if runtime is None and not self._settings.use_mock:
            try:
                runtime = self._get_runtime()
            except Exception:
                runtime = None
        return {
            "mode": "mock" if self._settings.use_mock else "model",
            "model_name": self._settings.model_name,
            "model_loaded": runtime is not None,
            "model_checkpoint_path": (
                str(self._settings.model_checkpoint_path.resolve())
                if self._settings.model_checkpoint_path is not None
                else None
            ),
            "device": runtime.metadata.device if runtime is not None else None,
            "runtime_error": self._runtime_error,
        }

    def _build_result(self, request: CreateJobRequest) -> dict[str, Any]:
        if self._settings.use_mock:
            return {
                "status": "Normal",
                "confidence": 93,
                "findings": [
                    "No supported chest pathology exceeded the configured screening threshold in this mock result.",
                    "Low-probability signals can still require clinical correlation if symptoms are present.",
                ],
                "recommendations": [
                    "Use this result as a screening aid and confirm through routine clinical review.",
                    "Escalate for professional interpretation if symptoms persist or if image quality is limited.",
                ],
                "ai_analysis": (
                    "This placeholder inference service completed a mock chest X-ray screening workflow and did not identify high-probability supported findings."
                ),
                "raw": {
                    "model_name": self._settings.model_name,
                    "model_version": self._settings.model_version,
                    "backbone": "densenet121",
                    "label_order": [
                        "Atelectasis",
                        "Cardiomegaly",
                        "Consolidation",
                        "Pneumonia",
                        "Pneumothorax",
                    ],
                    "probabilities": {
                        "Atelectasis": 0.12,
                        "Cardiomegaly": 0.11,
                        "Consolidation": 0.09,
                        "Pneumonia": 0.03,
                        "Pneumothorax": 0.01,
                    },
                    "thresholds": {
                        "Atelectasis": 0.5,
                        "Cardiomegaly": 0.5,
                        "Consolidation": 0.5,
                        "Pneumonia": 0.5,
                        "Pneumothorax": 0.5,
                    },
                    "predicted_positive_labels": [],
                    "top_labels": [
                        {"label": "Atelectasis", "probability": 0.12, "threshold": 0.5, "predicted_positive": False},
                        {"label": "Cardiomegaly", "probability": 0.11, "threshold": 0.5, "predicted_positive": False},
                        {"label": "Consolidation", "probability": 0.09, "threshold": 0.5, "predicted_positive": False},
                    ],
                    "image_quality": {
                        "image_type": "jpeg",
                        "quality_status": "ACCEPTABLE",
                        "warnings": [],
                        "width": 1024,
                        "height": 1024,
                    },
                    "explainability": {
                        "heatmap_url": None,
                        "explanation_text": None,
                    },
                },
            }

        runtime = self._get_runtime()
        return runtime.predict(request.object_key)

    def _get_runtime(self) -> LocalModelRuntime:
        if self._runtime is not None:
            return self._runtime

        with self._lock:
            if self._runtime is not None:
                return self._runtime
            try:
                self._runtime = LocalModelRuntime(self._settings)
                self._runtime_error = None
                return self._runtime
            except Exception as exc:
                self._runtime_error = str(exc)
                raise RuntimeError(f"failed to initialize local model runtime: {exc}") from exc


inference_service = InferenceService()
